#2016163: Added Lombok's @NonNull as default annotation
aditosoftware/adito-nb-modules pull request #22
Opened 2023-05-22 08:41 UTC by rH4rtinger

2023-05-22 10:02 UTC, L1nc0ln approved these changes

2023-06-14 06:40 UTC, L1nc0ln requested changes

2023-06-14 06:42 UTC, rH4rtinger commented on de-adito-blueprint-api/src/main/java/de/adito/nbm/blueprints/api/IBlueprint.java
> +import io.reactivex.rxjava3.annotations.Nullable;
ist korrigiert

2023-06-14 06:44 UTC, L1nc0ln approved these changes

2023-06-14 06:45 UTC, merged